// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateForm(ctx context.Context, arg CreateFormParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteForm(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetUserById(ctx context.Context, id string) (User, error)
	UpdateFormSchema(ctx context.Context, arg UpdateFormSchemaParams) error
	UpdateUserFirstName(ctx context.Context, arg UpdateUserFirstNameParams) error
	UpdateUserLastName(ctx context.Context, arg UpdateUserLastNameParams) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error
}

var _ Querier = (*Queries)(nil)
