// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user-queries.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, first_name, last_name, role) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateUserParams struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Role      string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM 
users
WHERE
id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT 
id, username, first_name, last_name, created_at, role 
FROM users
WHERE
id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const updateUserFirstName = `-- name: UpdateUserFirstName :exec
UPDATE users
SET 
first_name = $1
WHERE
id = $2
`

type UpdateUserFirstNameParams struct {
	FirstName string `json:"first_name"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateUserFirstName(ctx context.Context, arg UpdateUserFirstNameParams) error {
	_, err := q.db.Exec(ctx, updateUserFirstName, arg.FirstName, arg.ID)
	return err
}

const updateUserLastName = `-- name: UpdateUserLastName :exec
UPDATE users
SET 
last_name = $1
WHERE
id = $2
`

type UpdateUserLastNameParams struct {
	LastName string `json:"last_name"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateUserLastName(ctx context.Context, arg UpdateUserLastNameParams) error {
	_, err := q.db.Exec(ctx, updateUserLastName, arg.LastName, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET 
role = $1
WHERE
id = $2
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :exec
UPDATE users
SET 
username = $1
WHERE
id = $2
`

type UpdateUserUsernameParams struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUserUsername, arg.Username, arg.ID)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT 
count(*) 
FROM 
users
WHERE 
username = $1
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}
